import os

PROJECT_ID = os.getenv('_PROJECT_ID')
DATASET_MUDATA_RAW = os.getenv('_DATASET_MUDATA_RAW')
DATASET_MUDATA_CURATED = os.getenv('_DATASET_MUDATA_CURATED')
DATASET_MUDATA_AGGREGATED = os.getenv('_DATASET_MUDATA_AGGREGATED')
EXTERNAL_DATA_BUCKET = os.getenv('_EXTERNAL_DATA_BUCKET')

class BUSINESS_ROLES:
    TCC= 'TCC'
    TCP= 'TCP'
    BO= 'BO'
    AP= 'AP'
    AC= 'AC'
    AL= 'AL'